name: 'bde_at3'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
snapshot-paths: ["snapshots"]

models:
  bde_at3:
    +materialized: view
    gold:
      +schema: gold
      +materialized: table
